name: LoginBonusPlusPlus
main: me.pino.loginbonusplusplus.LoginBonusPlusPlus
version: 1.1.0
api-version: 1.16
author: pino223

commands:
  lb:
    description: Open login bonus GUI
    usage: /lb
    aliases: [loginbonus, lbp]

permissions:
  loginbonus.admin:
    description: Admin permission
    default: op